//
// market
//

export const SET_MARKET_TOP ='SET_MARKET_TOP';
export const SET_MARKET_LAST ='SET_MARKET_LAST';
export const GET_MARKET_TOP ='GET_MARKET_TOP';
export const GET_MARKET_LAST ='GET_MARKET_LAST';

//
// detail
//

export const GET_SYMBOL_QUOTES ='GET_SYMBOL_QUOTES';
export const SET_SYMBOL_QUOTES ='SET_SYMBOL_QUOTES';
export const GET_SYMBOL_LOGO ='GET_SYMBOL_LOGO';
export const SET_SYMBOL_LOGO ='SET_SYMBOL_LOGO';
export const GET_SYMBOL_NEWS ='GET_SYMBOL_NEWS';
export const SET_SYMBOL_NEWS ='SET_SYMBOL_NEWS';
export const GET_SYMBOL_CHART ='GET_SYMBOL_CHART';
export const SET_SYMBOL_CHART ='SET_SYMBOL_CHART';
export const GET_SYMBOL_TRADES ='GET_SYMBOL_TRADES';
export const SET_SYMBOL_TRADES ='SET_SYMBOL_TRADES';
export const GET_SYMBOL_BOOK ='GET_SYMBOL_BOOK';
export const SET_SYMBOL_BOOK ='SET_SYMBOL_BOOK';
export const GET_SYMBOL_COMPANY_INFO ='GET_SYMBOL_COMPANY_INFO';
export const SET_SYMBOL_COMPANY_INFO ='SET_SYMBOL_COMPANY_INFO';
export const GET_SYMBOL_PRICE ='GET_SYMBOL_PRICE';
export const SET_SYMBOL_PRICE ='SET_SYMBOL_PRICE';
